name: CI Pipeline

on:
  push:
    branches:
      - TDD
  pull_request:
    branches:
      - TDD

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pylint black flake8 isort

      # - name: Lint Python files with pylint
      #   run: |
      #     pylint interface.py classes.py tests.py

      # - name: Lint Python files with black and isort
      #   run: |
      #     black --check .
      #     isort --check-only .

      - name: Run SuperLinter
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: true
          VALIDATE_PYTHON_PYLINT: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests with coverage
        run: |
          pytest --cov=. --cov-report=term-missing --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
