name: CI Pipeline

on:
  push:
    branches:
      - TDD
  pull_request:
    branches:
      - TDD

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pylint

      - name: Run SuperLinter
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: true

      - name: Lint Python files with pylint
        run: |
          pylint interface.py classes.py tests.py

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage

      - name: Run unit tests with coverage
        run: |
          pytest --cov=interface --cov=classes --cov-report=term-missing
          coverage html
